

services:
  audio-seal:
    image: xiaoyao9184/audio-seal:main
    container_name: audio-seal-nb
    ports:
      - "8888:8888"
    volumes:
      - ./../../cache:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
